=== codeaudit/cougaar-logistics/bbn/config/glmtrans/AssetList.ldm.dtd
<!-- DTD definition of an ldm input file read by the UTILLdmXMLPlugin   -->
<!-- See org.cougaar.lib.plugin.UTILLdmXMLPlugin in the toolkit package -->
<!-- Gordon Vidaver, gvidaver@bbn.com, 617 873 3558                     -->

<!ELEMENT AssetList (prototype*, instance*)>

<!ELEMENT prototype (object)>
<!ATTLIST prototype name ID #REQUIRED>

<!ELEMENT instance (schedule)>
<!ATTLIST instance id ID #REQUIRED>
<!ATTLIST instance prototype CDATA #REQUIRED>

<!ELEMENT schedule EMPTY>
<!ATTLIST schedule start CDATA #REQUIRED>
<!ATTLIST schedule end   CDATA #REQUIRED>

<!ELEMENT object (field*)>
<!ATTLIST object class CDATA #REQUIRED>

<!ELEMENT field (value)>
<!ATTLIST field name ID #REQUIRED>
<!ATTLIST field type (char    | 
                      byte    | 
                      boolean |
                      short   | 
                      int     | 
                      long    | 
                      float   | 
                      double  | 
                      String  | 
                      object  | 
                      collection) #REQUIRED>

<!-- THIS ALLOWS OBJECT COMPOSITION -->

<!ELEMENT value (#PCDATA | object | collection)*>

<!ELEMENT collection (value*)>
<!ATTLIST collection type CDATA #REQUIRED>

=== codeaudit/cougaar-logistics/bbn/config/glmtrans/GlobalSea.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE assetlist SYSTEM "AssetList.ldm.dtd" [
<!ENTITY NetworkPrototypes SYSTEM "TransportationNetworkPrototypes.ldm.xml">
<!ENTITY SeaportPrototypes SYSTEM "SeaportPrototypes.ldm.xml">]>

<!--
/***********************************************************************************
 *                                                                                 *
 * This is open-source software developed by the TOPS team of BBN Technologies     *
 * under DARPA's ALPINE program. You can modify the software and redistribute it,  *
 * but you CANNOT DELETE OR MODIFY THIS COMMENT.                                   *
 *                                                                                 *
 * This software is distributed in the hope that it will be useful,                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                  *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            *
 *                                                                                 *
 * For details on the ALPINE open-source license please write:                     *
 * alpine-support@bbn.com                                                          *
 *                                                                                 *
 * Copyright (C) 1998, 1999 BBN Technologies                                       *
 *                                                                                 *
 ***********************************************************************************/
-->


<AssetList>

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                    First the Prototypes                     ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  &SeaportPrototypes;
  &NetworkPrototypes;

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                      Now the Instances                      ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  <instance prototype="SAVANNAH_PORT" id="SAVANNAH_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="BEAUMONT_PORT" id="BEAUMONT_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="SUNNY_POINT_PORT" id="SUNNY_POINT_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="GENOA_PORT" id="GENOA_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MASSAWA_PORT" id="MASSAWA_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MERSIN_PORT" id="MERSIN_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ISKENDERUN_PORT" id="ISKENDERUN_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="BREMERHAVEN_PORT" id="BREMERHAVEN_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ATHENS_PORT" id="ATHENS_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="PALERMO_PORT" id="PALERMO_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="NAPLES_PORT" id="NAPLES_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="LIVORNO_PORT" id="LIVORNO_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MONOPOLI_PORT" id="MONOPOLI_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ROTTERDAM_PORT" id="ROTTERDAM_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="IZMIR_PORT" id="IZMIR_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="FELIXSTOWE_PORT" id="FELIXSTOWE_PORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

</AssetList>

=== codeaudit/cougaar-logistics/bbn/configs/glmtrans/EuroShips.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE assetlist SYSTEM "AssetList.ldm.dtd" [
<!ENTITY NetworkPrototypes SYSTEM "TransportationNetworkPrototypes.ldm.xml">
<!ENTITY AmmoShipPrototypes SYSTEM "AmmoShipPrototypes.ldm.xml">
<!ENTITY ShipPrototypes SYSTEM "ShipPrototypes.ldm.xml">
<!ENTITY dummyprototypes SYSTEM "DummyPrototypes.ldm.xml">]>

<!--
-->

<AssetList>

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                    First the Prototypes                     ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  &ShipPrototypes;
  &AmmoShipPrototypes;
  &NetworkPrototypes;
  &dummyprototypes;

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                      Now the Instances                      ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

<!-- LMSR|RORO|Combo Ships -->

<!-- see http://www.msc.navy.mil/inventory/inventory.asp?var=LMSRship -->
<!-- for brief info on all these ships -->
<!-- BOZO : the prototype info is not right currently and needs to be updated -->
<!-- GWFV 01/17/01 -->

  <instance prototype="Bob_Hope_Prototype" id="Mendonca">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Gordon_Prototype" id="Gordon">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Gordon_Prototype" id="Gilliland">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Shughart_Prototype" id="Shughart">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Shughart_Prototype" id="Yano">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Bob_Hope_Prototype" id="Pililaau">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Watson_Prototype" id="Sisler">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>
</AssetList>

=== codeaudit/cougaar-logistics/bbn/configs/glmtrans/ShipPacker.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE assetlist SYSTEM "AssetList.ldm.dtd" [
<!ENTITY NetworkPrototypes SYSTEM "TransportationNetworkPrototypes.ldm.xml">
<!ENTITY AmmoShipPrototypes SYSTEM "AmmoShipPrototypes.ldm.xml">
<!ENTITY ShipPrototypes SYSTEM "ShipPrototypes.ldm.xml">
<!ENTITY dummyprototypes SYSTEM "DummyPrototypes.ldm.xml">]>

<!--
-->

<AssetList>

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                    First the Prototypes                     ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  &ShipPrototypes;
  &AmmoShipPrototypes;
  &NetworkPrototypes;
  &dummyprototypes;

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                      Now the Instances                      ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

<!-- LMSR|RORO|Combo Ships -->

  <instance prototype="Bob_Hope_Prototype" id="Bob_Hope">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Fisher_Prototype" id="Fisher">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Gilliland_Prototype" id="Gilliland">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Shughart_Prototype" id="Shughart">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Sisler_Prototype" id="Sisler">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Watson_Prototype" id="Watson">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Gordon_Prototype" id="Gordon">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Yano_Prototype" id="Yano">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

<!-- see http://www.msc.navy.mil/cgi-bin/inventory-ship.pl?var=Ammunitionship -->
<!-- for brief info on all these ships -->
<!-- BOZO : the prototype info is not right currently and needs to be updated -->
<!-- GWFV 01/17/01 -->

  <instance prototype="Butte_Prototype" id="Butte">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Flint">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Kilauea">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Kiska">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Mount_Baker">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Santa_Barbara">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Shasta">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Shasta_Mark_II">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>
</AssetList>

=== codeaudit/cougaar-logistics/bbn/configs/glmtrans/AmmoShips.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE assetlist SYSTEM "AssetList.ldm.dtd" [
<!ENTITY AmmoShipPrototypes SYSTEM "AmmoShipPrototypes.ldm.xml">]>

<AssetList>

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                    First the Prototypes                     ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  &AmmoShipPrototypes;

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                      Now the Instances                      ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

<!-- see http://www.msc.navy.mil/cgi-bin/inventory-ship.pl?var=Ammunitionship -->
<!-- for brief info on all these ships -->
<!-- As of 12/06/03 there are only 6 ammo ships listed -->
<!-- BOZO : the prototype info is not right currently and needs to be updated -->
<!-- GWFV 01/17/01 -->

  <instance prototype="Butte_Prototype" id="Butte">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Butte_Mark_II">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

<!--
  <instance prototype="Butte_Prototype" id="Butte_Mark_III">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>
-->

  <instance prototype="Butte_Prototype" id="Flint">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Kilauea">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Kiska">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Mount_Baker">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Santa_Barbara">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Butte_Prototype" id="Shasta">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>
</AssetList>

=== codeaudit/cougaar-logistics/bbn/configs/glmtrans/GlobalAir.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE assetlist SYSTEM "AssetList.ldm.dtd" [
<!ENTITY AirportPrototypes SYSTEM "AirportPrototypes.ldm.xml">]>

<!--
/***********************************************************************************
 *                                                                                 *
 * This is open-source software developed by the TOPS team of BBN Technologies     *
 * under DARPA's ALPINE program. You can modify the software and redistribute it,  *
 * but you CANNOT DELETE OR MODIFY THIS COMMENT.                                   *
 *                                                                                 *
 * This software is distributed in the hope that it will be useful,                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                  *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            *
 *                                                                                 *
 * For details on the ALPINE open-source license please write:                     *
 * alpine-support@bbn.com                                                          *
 *                                                                                 *
 * Copyright (C) 1998, 1999 BBN Technologies                                       *
 *                                                                                 *
 ***********************************************************************************/
-->


<AssetList>

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                    First the Prototypes                     ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  &AirportPrototypes;

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                      Now the Instances                      ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  <!-- APOEs for the Forts -->
  <instance prototype="SAVANNAH_INTL_AIRPORT" id="SAVANNAH_INTL_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="HUNTER_AAF" id="HUNTER_AAF">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="LAWSON_AAF" id="LAWSON_AAF">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ROBERT_GRAY_AAF" id="ROBERT_GRAY_AAF">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="POPE_AFB" id="POPE_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="LANGLEY_AFB" id="LANGLEY_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="RANDOLF_AFB" id="RANDOLF_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="PETERSON_AFB" id="PETERSON_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MCCHORD_AFB" id="MCCHORD_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <!-- AEF Airports-->
  <instance prototype="ATLANTIC_CITY" id="ATLANTIC_CITY">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="HOMESTEAD_AFB" id="HOMESTEAD_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="HOLLOMAN_AFB" id="HOLLOMAN_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="LAMBERT-ST_LOUIS" id="LAMBERT-ST_LOUIS">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="HILL_AFB" id="HILL_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="SHAW_AFB" id="SHAW_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ELMENDORF_AFB" id="ELMENDORF_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="SPANGDAHLEM_AFB" id="SPANGDAHLEM_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="LAKENHEATH" id="LAKENHEATH">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>   

  <instance prototype="EGLIN_AFB" id="EGLIN_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ELLSWORTH_AFB" id="ELLSWORTH_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="BEALE_AFB" id="BEALE_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="NELLIS_AFB" id="NELLIS_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="SEYMOUR_JOHNSON_AFB" id="SEYMOUR_JOHNSON_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="CANNON_AFB" id="CANNON_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="KADENA_AB" id="KADENA_AB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="RAMSTEIN_AFB" id="RAMSTEIN_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="PRINCE_SULTAN_AFB" id="PRINCE_SULTAN_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="AVIANO_AB" id="AVIANO">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance> 

  <!-- MEF Airports -->
  <instance prototype="MARCH_ARF" id="MARCH_ARF">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MIRAMAR_NAS" id="MIRAMAR_NAS">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="YUMA_NCAS" id="YUMA_NCAS">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="CHERRY_POINT_MCAS" id="CHERRY_POINT_MCAS">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="DIEGO_GARCIA_NSF" id="DIEGO_GARCIA_NSF">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <!-- REFUEL Airports -->
  <instance prototype="MORON" id="MORON">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ZARAGOZA" id="ZARAGOZA">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="RHEIN_MAIN_AFB" id="RHEIN_MAIN_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <!-- APOD Airports -->
  <instance prototype="ASMARA_AIRPORT" id="ASMARA_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MASSAWA_AIRPORT" id="MASSAWA_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ADEN_AIRPORT" id="ADEN_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ATAQ_AIRPORT" id="ATAQ_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MASIRAH_AIRPORT" id="MASIRAH_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ISKENDERUN_AIRPORT" id="ISKENDERUN_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="SANLIURFA_AIRPORT" id="SANLIURFA_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="ADANA_AIRPORT" id="ADANA_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="MARNEULI_AIRPORT" id="MARNEULI_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="VAZIANI_AIRPORT" id="VAZIANI_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <!-- European Airports-->
  <instance prototype="SIGONELLA_AIRPORT" id="SIGONELLA_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="PALERMO_AIRPORT" id="PALERMO_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="DECIMOMANNU_AIRPORT" id="DECIMOMANNU_AIRPORT">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="WIESBADEN_AB_AAF" id="WIESBADEN_AB_AAF">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="RAMSTEIN_AFB" id="RAMSTEIN_AFB">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

</AssetList>

=== codeaudit/cougaar-logistics/bbn/configs/glmtrans/ConusShips.ldm.xml
<?xml version="1.0"  encoding="US-ASCII"?>

<!DOCTYPE assetlist SYSTEM "AssetList.ldm.dtd" [
<!ENTITY NetworkPrototypes SYSTEM "TransportationNetworkPrototypes.ldm.xml">
<!ENTITY AmmoShipPrototypes SYSTEM "AmmoShipPrototypes.ldm.xml">
<!ENTITY ShipPrototypes SYSTEM "ShipPrototypes.ldm.xml">
<!ENTITY dummyprototypes SYSTEM "DummyPrototypes.ldm.xml">]>

<!--
-->

<AssetList>

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                    First the Prototypes                     ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

  &ShipPrototypes;
  &AmmoShipPrototypes;
  &NetworkPrototypes;
  &dummyprototypes;

  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->
  <!-- :::                      Now the Instances                      ::: -->
  <!-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -->

<!-- LMSR|RORO|Combo Ships -->

<!-- see http://www.msc.navy.mil/inventory/inventory.asp?var=LMSRship -->
<!-- for brief info on all these ships -->
<!-- BOZO : the prototype info is not right currently and needs to be updated -->
<!-- GWFV 01/17/01 -->

  <instance prototype="Bob_Hope_Prototype" id="Bob_Hope">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Bob_Hope_Prototype" id="Benavidez">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Bob_Hope_Prototype" id="Brittin">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Bob_Hope_Prototype" id="Fisher">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Bob_Hope_Prototype" id="Seay">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Watson_Prototype" id="Watson">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>

  <instance prototype="Watson_Prototype" id="Sisler">
    <schedule end="12/31/06" start="01/01/00"/>
  </instance>
</AssetList>
